### PR TITLE
convert from jekyll to zola

### PR DESCRIPTION
**Pull request by wikfeldt**

### CODE REVIEW

**Comment by wikfeldt** [comment]
I experienced dependency hell with ruby and jekyll on my new machine so figured the workshop template should be converted to Zola just like coderefinery.org. But these first steps are fumbling in the dark a bit.
@bast when you have time, can you have a look at give advice if something should be organised differently?

Todos:
- arbitrary number of logos now supported, but would be better to have them in a box on the right side rather than under title
- split into two columns? although i think single column looks fine 
- "improve this page" button in navigation bar not working. Setting a "repository_url" in config.toml and using it as `config.repository_url` in a template didn't work

**Comment by bast** [comment]
Great! Thanks for doing this. I will review and comment over the weekend. Let me know if you need this earlier in.

**Comment by wikfeldt** [comment]
thanks! no need to review by today, but early next week i think we'll need to have it for the hackathon page

**Comment by bast** [comment]
About the dependency hell: What I started doing when needing Jekyll is this: https://github.com/Starefossen/docker-github-pages

**Comment by bast** [comment]
I made few changes:
- two-column: I agree, single-column is simper
- logos: they are now in `config.toml`
- for `repository_url`: I moved it below `[extra]` - have a look how I am using `config.extra.logos`

**Comment by wikfeldt** [comment]
great, thanks for fixing this! i'll merge and if needed follow up in new PRs

**Pull request merged**
