### PR TITLE
add placeholder for questions, answers, and feedback

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by rkdarst** [comment]
- On the previous workshop webpage, I thought this section could have used some introduction about what it is and why it's there.
  - Hm... what about being in some other type of context box with a grey background to set it apart?  maybe it's overkill and an introduction would be enough...
- Is questions.md designed to be the template that gets copied to the hackpad?  If so, it could include some disclaimer that we will strip names and put it on the webpage.
  - From my understanding, it is already included, even before the workshop?  It takes some care to make the wording right for both.  But, if the jekyll can't handle it well, we don't need to do it.
  - can initial file be questions.md.TEMPLATE, and the section only appears when questions.md gets placed in the repo?

Random thoughts above, please rephrase into something coherent!

**Comment by bast** [comment]
Good points, I will adjust the PR and once it is accepted also visually adjust the real last workshop page.

**Comment by bast** [comment]
I think the rest are good questions/suggestions but somebody else should follow-up. Is it OK if I merge and make these issues?

**Comment by rkdarst** [comment]
Thanks, it's definitely good enough for now.  I made a new issue with the other comments.  They aren't that important and can be handled as it comes up and we think of better ideas over time.

**Pull request merged**
